language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: KcfE7vj7F9CR/3y5334bE3qzYw8mnzezLFwmYi3gQ0YAmKMuIhojvq1XPWKf4XGt2fS5+zih1xPYNtFKbzHGV+Ko1Wq4t8n1BNYzcRMUY7ta3gAaoKly2QFxVeDOuS3U8+Pbs08xJRoeQENTMKAFdQ/rgFmNNPK0dtNxu6LiMvcH86/XcOuLcgcvBWsSdFSTOhhm0B60XzXcc/IStkrmHGWdcs5P7NEsXTbF+k7sHVDK7DFu6F+ckhsvo45lM1E4JfifuCpHyX4tXkBr75PijeYQxlv+RVp1lRwk2febjmcLYSX8spvIx1NYPgp3ovLqkKGZFL0hjhQTE1A7jK4zDEhFLs0QnCLbgtumarLKS1+DTQrpfjlElyyVDkVAL36npesLHdc2FejtLwqZEa0m/oAKXhu2I8+VtytkGLtg8Jj9gDEgZ0+X/eMcb84shON4tpc758CeUTZyQMNHGxy3jc0GUE78bGElSYksmVWTLAG6owQRb9i0mPxX5vnhDDRrleri3twFBLHaWD4LNlBPdmJJtwxJII0T7UAKcmXd8vGTx3uWkGV6P7BQfSDVaC6wAYnhy7cV2w4n0ZF84opKryJO/IyQzQtyJkZc161mp7sP9fPwHM/RxYeof7UZvRJnDmtdM5PqtsGvBsQXT5F3ptqIP1uZsaUPlGOXDcnbkFw=
  app: jogo-da-velha
