language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: "cSNEGdT5/HpccmYdu2z6n8K+s1E7W6kphrmITCaNxgJsosWOJJ1rVNVdSu5DhZEFiHQSCA5YzBeUGJypAb75t/8pvZuOAcUY7/CbRmXAr1j8TKtWbIDD08TLQaXaEih5wzsMVqtGGzYXh2FpWNDsEcZr9f9pdOIfoBR2NfgKvy2vFAT+n9kYwtm7BpiNRS1xzVEEAYe/HCstBMQUnJth39Q9wsrcdV8OZtrKgOx4xL5QW1+8L+tTxO43LFR4Cu2PklWCw0zaalkGkD4Xaas2ZVdszZbO9PhpbMpKzUSnuH9+WcRwZhIGypr7HpXCIgUGFf+N2NJWn6HQPDf9n9T928AZBWalpmw2D/nrRIERy3qhQ2db9ntg5VGKC/R0TfNWSllVgptIzUNfPNOtY/kqDRRC07hotWFHvsL8ExKfbPlmQg3H3Gq9qT4LVFycquSUgfz7bEsgdv6PlNpu9it13T12T6dNY/jJxTYmToige7qFGvHMcVXvl47RmB53agX0poj10CDuB5mQ75SrCU2bGzMcYjnvwDHxGCZoLVzIhW9D6cgNeRw5D8WKAVFWXRYAv6K6SNVClEFJ7mgz50Dah5OWBxQUAb3QWyOLo3MAyqzGnlmRU9rSCg1x1xbpU8qZoKhuc38YBUbbZk4sCkHn67r0Xd2y1WM5J7yBTNp7QNU="
  app: jogo-da-velha
